# Generated by Django 5.0.1 on 2024-08-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
