# Generated by Django 5.0.1 on 2024-08-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_category_order_entry_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
