# Generated by Django 5.0.1 on 2024-06-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.PositiveIntegerField(default=0)),
                ('parent_tax_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('rank', models.CharField(default='', max_length=200)),
                ('version', models.ManyToManyField(to='taxonomy.version')),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(unique=True)),
                ('assembly_level', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('group', models.CharField(default='', max_length=200)),
                ('file', models.FileField(default='', upload_to='data/genomes')),
                ('taxon', models.ForeignKey(on_delete=set, to='taxonomy.taxon')),
                ('version', models.ManyToManyField(to='taxonomy.version')),
            ],
        ),
    ]
