# Generated by Django 5.0.1 on 2024-06-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomic_signature', models.FloatField()),
                ('biobit', models.FloatField()),
                ('number_bases', models.PositiveBigIntegerField()),
                ('annotated_genes', models.PositiveIntegerField()),
                ('protein_coding_genes', models.PositiveIntegerField()),
                ('non_coding_genes', models.PositiveIntegerField()),
                ('hapaxes', models.FloatField()),
                ('gc_content', models.FloatField()),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.genome')),
            ],
        ),
    ]
