# Generated by Django 4.2.7 on 2023-11-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taxonomy',
            table='taxonomy',
        ),
    ]
