# Generated by Django 5.0.1 on 2024-06-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traits',
            name='number_bases',
        ),
        migrations.AddField(
            model_name='traits',
            name='genome_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traits',
            name='number_acgt_bases',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
