# Generated by Django 4.2.7 on 2023-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_alter_taxonomy_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='tax_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
