# Generated by Django 5.0.1 on 2024-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_remove_traits_number_bases_traits_genome_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traits',
            name='entropy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traits',
            name='k1_bb',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traits',
            name='k_gs',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
