# Generated by Django 4.2.7 on 2023-11-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_taxonomy_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='parent_tax_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='rank',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='unique_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
