# Generated by Django 5.0.1 on 2024-06-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_traits_entropy_traits_k1_bb_traits_k_gs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traits',
            name='genome',
        ),
        migrations.AddField(
            model_name='genome',
            name='trait',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='taxonomy.traits'),
        ),
    ]
