# Generated by Django 4.2.7 on 2023-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_taxonomy_name_taxonomy_parent_tax_id_taxonomy_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='id',
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='tax_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
