# Generated by Django 4.2.7 on 2023-12-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_remove_taxonomy_id_alter_taxonomy_tax_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('tax_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('parent_tax_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('unique_name', models.CharField(default='', max_length=200)),
                ('rank', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Taxonomy',
        ),
        migrations.AddField(
            model_name='taxon',
            name='version',
            field=models.ManyToManyField(to='taxonomy.version'),
        ),
    ]
