# Generated by Django 4.2.7 on 2023-12-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_genome'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='file',
            field=models.FileField(default='', upload_to='data/genomes'),
        ),
    ]
