# Generated by Django 4.2.7 on 2023-12-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_genome_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='unique_name',
        ),
    ]
