# Generated by Django 5.0.1 on 2024-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_genome_assembly_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='genome',
            name='group',
            field=models.CharField(default='', max_length=200),
        ),
    ]
